---
apiVersion: v1
kind: Service
metadata:
  name: cal-ser
  labels:
    name: cal-ser
    app: calculator-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: cal-pod
    app: calculator-app
    